server:
  port: 8000

spring:
  #  config:
  #    import: "optional:configserver:http://localhost:8888/"
  cloud:
    #    config:
    #      name: msa
    #      profile: gateway
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/core/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizedUserJwtFilter
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/ai/**

        - id: scheduler-service
          uri: lb://scheduler-service
          predicates:
            - Path=/sc/**
        - id: mail-service
          uri: lb://mail-service
          predicates:
            - Path=/mail/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizedUserJwtFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/verify
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizedUserJwtFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/password
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizedUserJwtFilter

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**


  application:
    name: gateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://host.docker.internal:8761/eureka
      defaultZone: http://localhost:8761/eureka
