server:
  port: 8081

spring:
#  config:
#    import: "optional:configserver:http://localhost:8888/"
#  cloud:
#    config:
#      name: msa
#      profile: member
  application:
    name: scheduler-service


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://wasuphj.synology.me:8761/eureka
#      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.moment.scheduler: debug

feign:
  client:
    config:
      default:
        connectTimeout: 500000
        readTimeout: 500000
