name: Deploy

on:
  push:
    branches:
      - deploy/v1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17  # 원하는 Java 버전으로 변경
          distribution: 'temurin'

      - uses: actions/checkout@v3

      - run: touch ./backend/moment/moment-server/auth/src/main/resources/application.properties
      - run: echo "${{ secrets.AUTH_PROPERTIES }}" > ./backend/moment/moment-server/auth/src/main/resources/application.properties

      - run: touch ./backend/moment/moment-server/core/src/main/resources/application.properties
      - run: echo "${{ secrets.CORE_PROPERTIES }}" > ./backend/moment/moment-server/core/src/main/resources/application.properties

      - run: touch ./backend/moment/moment-server/mail/src/main/resources/application.properties
      - run: echo "${{ secrets.MAIL_PROPERTIES }}" > ./backend/moment/moment-server/mail/src/main/resources/application.properties

      - run: touch ./backend/moment/moment-server/scheduler/src/main/resources/application.properties
      - run: echo "${{ secrets.SCHEDULER_PROPERTIES }}" > ./backend/moment/moment-server/scheduler/src/main/resources/application.properties


#      - run: cat ./src/main/resources/application.properties

      - name: Set up Gradle
        uses: eskatos/setup-gradle@v1
        with:
          gradle-version: <desired_gradle_version>


      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Deploy to Server
        uses: actions/checkout@v3

      - run: |
          cd ./backend/moment/moment-server
          docker-compose up --build

          # 서버에 애플리케이션 배포 스크립트 실행
        # 예: scp, SSH, Docker, Kubernetes 등을 사용하여 배포
  deploy:

    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - name: Add Server key
        run: |
          touch key.txt && echo "${{ secrets.SERVER_KEY }}" > key.txt
          chmod 600 key.txt
      - name: Deploy the application
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          chmod 755 ./deploy.sh
          set -e
          ./deploy.sh